- name: "security_zones.address_books: Ensure state of address-book objects {{ security_zone.name }}" 
  junos_config:
    lines:
      - set security zones security-zone {{ security_zone.name }} address-book address {{ address_book.name }} {{ address_book.ipv4 | ipaddr('address') }}
