---

- name: application input splitting to list
  set_fact:
    app_cache: "{% if dest_applications is iterable and dest_applications is not string %}{{dest_applications}}
      {% else %}{{ dest_applications.split('\n') }}{% endif %}"
  when: survey

- name: match applications to panos format
  set_fact:
    applications: "{{ applications + [__appmatch[item]] }}"
  loop: "{{ app_cache }}"
  when: survey

- name: apps
  debug:
    msg: "{{ applications }}"
  tags: debug