

- name: Juniper Firewall Play
  hosts: junos
  connection: netconf
  gather_facts: False
  roles:
    - junosfw

- name: Palo Alto Firewall 
  hosts: panos
  connection: local
  gather_facts: False
  roles:
    - panos
