

security_policy:
  name: "{{ src_hostname }}_{{ dest_hostname }}"
  from: "{{ 'outside' if src_zone == 'dmz' else src_zone }}"
  to: "{{ 'outside' if dest_zone == 'dmz' else dest_zone }}"
  source_addresses:
    - name: "{{ src_hostname }}"
  destination_addresses:
    - name: "{{ dest_hostname }}"
  applications: "{{ applications }}"
  actions:
   - "{{ fw_action }}"
  